ishkawa/APIKit

- APIKit/APIKit.swift
- APIKit/RequestBodyBuilder.swift
- APIKit/ResponseBodyParser.swift
- APIKit/URLEncodedSerialization.swift
- APIKitTests/RequestBodyBuilderTests.swift
- APIKitTests/ResponseBodyParserTests.swift
- `success`
- `failure`
- `try`
- `Result.flatMap`
> Use helper functions for Result

- README.md
As per documentation: https://github.com/Carthage/Carthage
**Note that Carthage only supports dynamic frameworks, which are only available on iOS 8 or later (or any version of OS X).**
> Fix iOS deployment target in README

- APIKit/APIKit.swift
- APIKitTests/APITests.swift
> Add `responseErrorFromObject` to create detailed error using response object

- APIKit/APIKit.swift
- APIKitTests/APITests.swift
- README.md
This resolves #13. This change makes implementation simpler and more obvious.
- Add defaultURLSession that has a delegate with minimal implementation of NSURLSessionDataDelegate.
- Remove instance pair, which is singleton instance pair of API and NSURLSession.
Breaking changes:
- `API` does not creates singleton instances for each API subclasses. If an `API` subclass needs a separated session, `defaultURLSession` should be overrided.
- `API.instance` is no longer available.
- `API.session` is no longer available.
- Delegate methods implemented in `API` should be moved to custom delegate class, and its instance should be set to delegate of `defaultURLSession`.
See the discussion on #13 for more details.
> Add defaultURLSession and its delegate instead of instancePair

- APIKit/APIKit.swift
- APIKitTests/APITests.swift
- README.md
- Add `cancelRequest(_:passingTest:)`.
- Add `cancelRequest(_:URLSession:passingTest:)` to cancel requests in a specific URL session.
On iOS 7 and Mac OS 10.9, the actual objects created by `dataTaskWithRequest:` returns `false` for `task is NSURLSessionTask`. It causes failure of casting task to `NSURLSessionTask`, so getting `request` from task `(task as? NSURLSessionTask)?.request` always fails. To avoid this, implementation of `isKindOfClass:` for following classes are modified.
- `__NSCFLocalSessionDataTask`
- `__NSCFLocalSessionDownloadTask`
- `__NSCFLocalSessionUploadTask`
Because they are private classes, sample instances of them are created once in `initialize()` to access them.
> Add `cancelRequest(_:passingTest:)` for cancellation

- APIKit/API.swift
Because we are passing a request between a download task and a data task, we should avoid unnecessary boxing which is implicitly applied.
> Explicit request boxing for Tasks

- APIKit/API.swift
- APIKit/Request.swift
- APIKitTests/APITests.swift
- APIKitTests/RequestBodyBuilderTests.swift
- APIKitTests/ResponseBodyParserTests.swift
- DemoApp/GitHub.swift
This is a breaking change. Is there any specific needs of per request response building?
Additionally, the request parameter of `sendRequest` is not captured in a task's completion handler any more.
> Change `Request.responseFromObject` to class func

- APIKit.xcodeproj/xcshareddata/xcschemes/APIKit-Mac.xcscheme
- APIKit.xcodeproj/xcshareddata/xcschemes/APIKit-iOS.xcscheme
To detect issues caused by the compiler optimization. Both iOS and Mac tests are passing on my Machine.
> Specify Release configuration for test build

- APIKitTests/APITests.swift
- DemoApp/GitHub.swift
These are not needed anymore in Swift 1.2, they can be compiled now.
> Remove unnecessary overriding

- .gitmodules
- Cartfile.private
- Cartfile.resolved
[4.0.0](https://github.com/AliSoftware/OHHTTPStubs/blob/b5742078af2032c93f51c6dd47f401d89bf2cc23/CHANGELOG.md#400--improvements-for-swift) was released with Carthage support (from 3.1.11) and some improvements for Swift.
> Switch to original OHHTTPStubs

- APIKit/API.swift
Sometimes want to set a custom requestBodyBuilder for individual endpoint.
So use API requestBodyBuilder as a default and add a parameter to specify custom requestBodyBuilder.
> Add custom requestBodyBuilder argument to URLRequest

- APIKit/API.swift
- APIKitTests/APITests.swift
- DemoApp/GitHub.swift
- README.md
I wrote `func URLRequest(_:_:_:)` in early version of APIKit to make code shorter, but this sacrifices readability and flexibility of argument. So I suggest to deprecate this method and add `func URLRequest(method:path:parameters:requestBodyBuilder:)`.
```swift
var URLRequest: NSURLRequest? {
return GitHub.URLRequest(.GET, "/search/repositories", ["q": query, "sort": sort.rawValue, "order": order.rawValue])
}
```
```swift
var URLRequest: NSURLRequest? {
return GitHub.URLRequest(
method: .GET,
path: "/search/repositories",
parameters: ["q": query, "sort": sort.rawValue, "order": order.rawValue]
)
}
```
In new method, we can skip `parameter` argument like below. This can be useful to set ad hoc `requestBodyBuilder` for a specific endpoint (added in #31).
```swift
var URLRequest: …
```
> Deprecate `URLRequest` with implicit parameter labels

- APIKit/API.swift
- APIKit/ResponseBodyParser.swift
- Cartfile.resolved
Some API returns 204 and it make a parse error.
So avoid call responseBodyParser and passing dummy data to responseFromObject.
> Avoid parsing when status is 204.

- APIKit/API.swift
This is intended for modifying the returned request in subclasses which override the method, or in `Request` protocol conforming types who call the method in their `URLRequest` property.
This is useful for the cases like: adding HTTP header fields, per endpoint timeout interval, etc.
> Change return type of URLRequest(method:path:parameters:requestBodyBuilder) to NSMutableURLRequest

- APIKit/HTTPMethod.swift
> If an element of an enum with string raw type does not have an explicit raw value, it will default to the text of the enum’s name.
from [Release Notes](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_7_beta_3/Xcode_7_beta_3_Release_Notes.pdf).
> Updates for Xcode 7 beta 3

- APIKit/API.swift
- APIKit/URLEncodedSerialization.swift
This is a rebased version of #43.
:warning:  __This is a breaking change.__ :warning: 
It seems to me that those changed are not meant to be extended or overridden.
But I'm concerned about `API.sendRequest()` method, overriding that might be useful if someone want to modify the returned data task (e.g. set `taskDescription` or `taskIdentifier`).
> More adoption of `static` and `final`

- APIKit/URLEncodedSerialization.swift
Some API GET parameter contains array [ ]. So GET parameter need escaping.
> Dict get parameter

- APIKit/URLEncodedSerialization.swift
Thanks for the marvelous library.
`CFURLCreateStringByAddingPercentEscapes` is deprecated since iOS9 SDK.
https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/Objective-C/CoreFoundation.html
APIKit uses this API at https://github.com/ishkawa/APIKit/blob/master/APIKit/URLEncodedSerialization.swift#L4
Therefore, I replaced this deprecated API with `stringByAddingPercentEncodingWithAllowedCharacters` method based on [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt).
I'd appreciated it if you would review this PR when you have enough time.
> Escape via stringByAddingPercentEncodingWithAllowedCharacters

- APIKit/API.swift
- APIKit/Request.swift
- APIKitTests/RequestCreateTaskInURLSessionTests.swift
Exposing final NSURLRequest makes debugging easy.
In early beta, NSURLSession.sendRequest() returned NSURLSessionDataTask?, so we had to handle errors of this method. The purpose of createTaskInURLSession() was putting error handling into 1 place, but now it is not necessary.
> Replace createTaskInURLSession() with buildURLRequest()

- APIKit/RequestType.swift
- APIKit/URLEncodedSerialization.swift
- APIKitTests/RequestCreateTaskInURLSessionTests.swift
- APIKitTests/RequestTests.swift
Fixed parameter handling when its value is null.
For example, there are some scenarios when `some_api?query=&page=1` should be replaced as `some_api?query&page=1` (no `query=`).
> Fix parameter type from [String:AnyObject] to [String:AnyObject?] for nullable value.

- APIKit/RequestType.swift
This fix will be helpful if one wants to use `RequestType` without pre-installed `Session` class.
In my case, there is already a custom session client class (which doesn't use NSURLSession).
> Change access level of RequestType.parseData() to public.

- APIKit/RequestType.swift
Because `parameters` computed property in RequestType protocol is called twice in it's `buildURLRequest` method, I bind it to local variable once.
---
`RequestType` プロトコルの `parameters` プロパティが重複して呼ばれるので、一度ローカル変数にセットするようにしてみました。
> stop calling parameters variable twice

- .travis.yml
It is already installed and will cause Travis build to fail.
If you want to use the latest version of `carthage`, here is the only
way (works but dirty) that I know:
brew uninstall carthage && brew install carthage
> Remove "brew install carthage"

- Demo.playground/Contents.swift
This function has been deprecated in favor of `XCPlaygroundPage.needsIndefiniteExecution`.
> Replace the deprecated function `XCPExecutionShouldContinueIndefinitely()`

- APIKit/RequestType.swift
- APIKitTests/RequestTypeTests.swift
> Add arrayParameters to RequestType protocol

- APIKit.xcodeproj/project.pbxproj
- Sources/Box.swift
- Sources/NSURLSessionAdapter.swift
- Sources/Session.swift
- Sources/SessionAdapterType.swift
There're some feature requests that Alamofire provides, for example #129 and #121, but I would like to keep APIKit as simple as possible. To satisfy the both needs, I decided to make the backend abstract. On the new architecture, we can build `Session` both on `NSURLSession` and `Alamofire.Manager`.
This PR introduces 2 new protocols, `SessionAdapterType` and `SessionTaskType`:
```swift
public protocol SessionAdapterType {
func resumedTaskWithURLRequest(URLRequest: NSURLRequest, handler: (NSData?, NSURLResponse?, NSError?) -> Void) -> SessionTaskType
func getTasksWithHandler(handler: [SessionTaskType] -> Void)
}
public protocol SessionTaskType: class {
func cancel()
}
```
`SessionAdapterType` provides an interface to get `(NSData?, NSURLResponse?, NSError?)` from `NSURLRequest` and …
> Abstraction of backend

- README.md
related #151 
Since Himotoki 2.0, `Decodable.DecodedType` has been removed https://github.com/ikesyo/Himotoki/blob/204e79dcef75595cb0a1cec4a53a82e6fdaf9e40/Sources/Decodable.swift#L9-L12 
so the consistent `Self.Response == Self.Response.DecodedType` doesnt work.
> Remove type constraint from example code

- README.md
since Himotoki's API has been changed, `decode` is renamed to `decodeValue` 
ref: https://github.com/ikesyo/Himotoki/pull/96
> Rename method name in README, decode to decodeValue

- APIKit.xcodeproj/project.pbxproj
- Sources/CallbackQueue.swift
- Sources/Session.swift
- Tests/APIKit/SessionCallbackQueueTests.swift
Extended version of #156.
This PR provides following types of queues:
```swift
/// `CallbackQueue` represents queue where `handler` of `Session.sendRequest(_:handler:)` runs.
public enum CallbackQueue {
/// Dispatches callback closure on main queue asynchronously.
case Main
/// Dispatches callback closure on the queue where backend adapter callback runs.
case SessionQueue
/// Dispatches callback closure on associated operation queue.
case OperationQueue(NSOperationQueue)
/// Dispatches callback closure on associated dispatch queue.
case DispatchQueue(dispatch_queue_t)
}
```
`callbackQueue` parameter is added to the components below:
```swift
Session {
public init(adapter: SessionAdapterType, callbackQueue: CallbackQueue = .Main)
public func sendRequest<Request: RequestType>(request: …
```
> Add CallbackQueue

- Sources/Session.swift
As discussed in #155, changing these components from `static` to `class` allows us to extend shared Session behavior.
> Change sharedSession and related methods from `static` to `class`

- Sources/Session.swift
This PR brings #158 into 2.0 branch.
> [2.0] Change sharedSession and related methods from `static` to `class`

- Sources/Error/RequestError.swift
- Sources/Error/SessionTaskError.swift
- Sources/RequestType.swift
- Sources/Session.swift
- Sources/SessionAdapterType/NSURLSessionAdapter.swift
- Sources/SessionAdapterType/SessionAdapterType.swift
- Tests/APIKit/RequestTypeTests.swift
- Tests/APIKit/SessionAdapterType/NSURLSessionAdapterTests.swift
- Tests/APIKit/SessionTests.swift
- Tests/APIKit/TestComponents/TestRequest.swift
- Tests/APIKit/TestComponents/TestSessionAdapter.swift
- Tests/APIKit/TestComponents/TestSessionTask.swift
In NSURLSession, entire behavior of HTTP/HTTPS request is defined by combination of NSURLRequest, NSURLSessionTask and NSURLSessionConfiguration. In current 2.0 implementation, RequestType expresses HTTP/HTTPS request in NSURLRequest only, so some features of NSURLSession is unavailable. For instance, `uploadTaskWithStreamedRequest(_:)` and `uploadTaskWithRequest(_:fromData)`.
To remove the limitation, I moved responsibility of building backend request like NSURLRequest to SessionAdapterType. In the new implementation, NSURLSessionAdapter can express requests combining NSURLRequest and NSURLSessionTask.
- [**Removed**] `buildURLRequest()`
- [**Added**] `buildURL()`
- [**Removed**] `HTTPHeaderFields`
- [**Added**] `headerFields`
- [**Removed**] `func resumedTaskWithURLRequest(_:handler:)` …
> Move building backend request like NSURLRequest to SessionAdapterType

- Sources/RequestType.swift
- Tests/APIKit/RequestTypeTests.swift
> Use return value of configureURLRequest(_:)

- APIKit.xcodeproj/project.pbxproj
- Sources/SessionAdapterType/NSURLSessionAdapter.swift
- Tests/APIKit/SessionAdapterType/NSURLSessionAdapterSubclassTests.swift
- Tests/APIKit/SessionAdapterType/NSURLSessionAdapterTests.swift
Currently, subclassing NSURLSessionAdapter is not working because its delegate methods are not used.
> Fix subclassing NSURLSessionAdapter

- Sources/Session.swift
> Replace unused argument with underscore

- Documentation/DefiningRequestProtocolForWebService.md
Trivial fix for doc example codes.
> Fix examples in defining-request-protocol doc

- Sources/Session.swift
- Sources/SessionAdapter/SessionAdapter.swift
- Sources/SessionAdapter/URLSessionAdapter.swift
- Tests/APIKit/SessionTests.swift
- Tests/APIKit/TestComponents/TestSessionAdapter.swift
- Tests/APIKit/TestComponents/TestSessionTask.swift
For consistency with the other protocols such as Request, SessionAdapter and BodyParameters.
> Rename SessionTaskType to SessionTask

- Sources/Session.swift
- Tests/APIKit/SessionAdapterType/URLSessionAdapterTests.swift
- Tests/APIKit/SessionTests.swift
- codecov.yml
- Rename `Session.sharedSession` to `Session.shared`.
- Rename `cancelRequests(withType:passingTest:)` to `cancelRequests(with:passingTest:)`.
In #194, I said that the first label of cancel method needs the word "Type", but it apparently expresses  type of requests even if the argument label does not have "Type" 🙇
> Refine Session APIs for Swift 3

- APIKit.xcodeproj/project.pbxproj
- Sources/APIKit/BodyParameters/ProtobufBodyParameters.swift
- Sources/APIKit/DataParser/ProtobufDataParser.swift
- Tests/APIKitTests/BodyParametersType/ProtobufBodyParametersTests.swift
- Tests/APIKitTests/DataParserType/ProtobufDataParserTests.swift
It would be great to have Protocol Buffers support in APIKit. I added `ProtobufDataParser` and `ProtobufBodyParameters` for its use case since JSON content type is default.
See detailed info [here](https://developers.google.com/protocol-buffers/).
```
protocol ProtobufRequest: Request {}
extension ProtobufRequest {
var baseURL: URL {
return URL(string: "http://localhost:8080")!
}
var dataParser: DataParser {
return ProtobufDataParser()
}
}
extension ProtobufRequest where Response: ProtobufGeneratedMessage {
func response(from object: Any, urlResponse: HTTPURLResponse) throws -> Response {
guard let data = object as? Data else {
throw ResponseError.unexpectedObject(object)
}
return try Response(protobuf: data)
}
}
struct MyModelRequest: ProtobufRequest {
typealias Response = MyModel
var …
```
> Support protocol buffers

- Sources/APIKit/CallbackQueue.swift
Changes the access control of CallbackQueue.execute() to `public` from `internal` for using outside of APIKit module.
> Issue #220 Changes the access control of CallbackQueue.execute()

- .gitignore
- Sources/APIKit/DataParser/DataParser.swift
- Sources/APIKit/Request.swift
- Tests/APIKitTests/SessionTests.swift
- Tests/APIKitTests/TestComponents/TestRequest.swift
DataParser should not be required to return Any and have objects checked for type safety at runtime. This PR allows us to use the Swift build time type checking system with very minimal changes to existing code. The only API breaking change is that Request classes using the default JSONDataParser should now conform to JSONRequest, instead of just Request. This is because protocol extensions cannot declare default associated types.
> Data parser associated types

- Sources/APIKit/Session.swift
- Sources/APIKit/SessionAdapter/SessionAdapter.swift
- Sources/APIKit/SessionAdapter/URLSessionAdapter.swift
- Tests/APIKitTests/SessionAdapterType/URLSessionAdapterSubclassTests.swift
- Tests/APIKitTests/SessionTests.swift
- Tests/APIKitTests/TestComponents/TestSessionAdapter.swift
- Tests/APIKitTests/TestComponents/TestSessionTask.swift
See: https://github.com/ishkawa/APIKit/issues/186
Add `progressHandler(bytesSent:totalBytesSent:totalBytesExpectedToSend:)` parameter in `Session.send` for getting progress of uploading.
While the upload is in progress, `progressHandler` closure in `Session.send` is periodically called.
Therefore you can get information of uploading about `didSendBodyData` `totalBytesSent` `totalBytesExpectedToSend`.
These parameters are defined by `urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)` in [URLSessionTaskDelegate](https://developer.apple.com/reference/foundation/urlsessiontaskdelegate/1408299-urlsession).
```swift
Session.send(request, 
progressHandler: { bytesSent, totalBytesSent, totalBytesExpectedToSend in
let progress = Float(totalBytesSent) / …
```
> Add a way to get progress of uploading.

- Sources/APIKit/SessionAdapter/URLSessionAdapter.swift
- Tests/APIKitTests/SessionAdapterType/URLSessionAdapterSubclassTests.swift
```progressHandler(bytesSent:totalBytesSent:totalBytesExpectedToSend:)``` parameter in ```Session.send``` is not working.
The reason is ```progressHandler``` getter reference the wrong key in ```URLSessionAdapter.swift```
So fix it and write unit test!
> Fix `progressHandler` to work properly

- Sources/APIKit/Request.swift
The name `Parser` is a little bit ambiguous because there're some other things to parse around Request. I have renamed this associated type as `DataParser` to declare that this type parses `Data` explicitly.
> Rename Request.Parser to Request.DataParser

- APIKit.podspec
Because of typo in the podspec file, I couldn't install using Cocoapods by specifying repository and tag. I fixed this typo.
**Podfile description**
```ruby
pod 'APIKit', :git => 'https://github.com/ishkawa/APIKit.git', :tag => '3.2.0'
```
**Installation Error**
```shell
$ pod install
Analyzing dependencies
Pre-downloading: `APIKit` from `https://github.com/ishkawa/APIKit.git`, tag `3.2.0`
[!] Failed to load 'APIKit' podspec: 
[!] Invalid `APIKit.podspec` file: undefined method `pod_target_xcconfigs=' for #<Pod::Specification name="APIKit">.
>    s.pod_target_xcconfigs = { "SWIFT_VERSION" => "4.0" }
```
> Fix typo in the podspec file

- Sources/APIKit/Request.swift
`unacceptableStatusCode` belongs to `ResponseError` instead of `RequestError`.
> Fix a typo in Request.intercept.

- Sources/APIKit/BodyParameters/Data+InputStream.swift
`UnsafeMutablePointer.deallocate(capacity:)` is deprecated in Swift 4.1.
> 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
Since we deallocates entire heap blocks originally, we can just replace `deallocate(capacity:)` with `deallocate()` as compiler suggests.
> Use buffer.deallocate() instead of buffer.deallocate(capacity:) in Swift 4.1 or later

- .travis.yml
- Tests/APIKitTests/BodyParametersType/ProtobufBodyParametersTests.swift
- Tests/APIKitTests/DataParserType/ProtobufDataParserTests.swift
This also adds a temporary fix for building the tests with Xcode 10.2.
> [CI] Refactor .travis.yml

- Sources/APIKit/BodyParameters/JSONBodyParameters.swift
- Tests/APIKitTests/BodyParametersType/JSONBodyParametersTests.swift
There are redundant codes for initializing `JSONBodyParameters`.
I make it possible to initialize simply from Dictionary Literal.
```swift
let object = ["foo": 1, "bar": 2, "baz": 3]
let parameters = JSONBodyParameters(JSONObject: object)
```
```swift
let parameters: JSONBodyParameters = ["foo": 1, "bar": 2, "baz": 3]
```
or
```swift
let parameters = ["foo": 1, "bar": 2, "baz": 3] as JSONBodyParameters
```
> ExpressibleByDictionaryLiteral for JSONBodyParameters
