ishkawa/APIKit

.gitignore
.gitmodules
APIKit.xcodeproj/project.pbxproj
APIKit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
APIKitTests/RequestBodyBuilderTests.swift
APIKitTests/ResponseBodyParserTests.swift
Cartfile.private
Cartfile.resolved

Use the fork for Swift 1.1 support: https://github.com/neilpa/Assertions/tree/swift-1.1

Introduce Assertions.framework for test target

---

APIKit.xcodeproj/xcshareddata/xcschemes/APIKit-Mac.xcscheme
circle.yml

Update circle.yml for Xcode 6.3

---

.gitmodules
APIKit.podspec
APIKit.xcodeproj/project.pbxproj
APIKit.xcodeproj/xcshareddata/xcschemes/APIKit-Mac.xcscheme
APIKit.xcodeproj/xcshareddata/xcschemes/APIKit-iOS.xcscheme
APIKit/API.swift
APIKit/RequestBodyBuilder.swift
APIKit/ResponseBodyParser.swift
APIKitTests/APITests.swift
APIKitTests/RequestBodyBuilderTests.swift
APIKitTests/ResponseBodyParserTests.swift
Cartfile
Cartfile.resolved
DemoApp/GitHub.swift
DemoApp/ViewController.swift
README.md
circle.yml

I have replaced LlamaKit with Result, which is announced as an alternative of LlamaKit officially.

Goodbye LlamaKit

---

.gitmodules
README.md

Addresses #40.
We should bootstrap or update the dependencies with the command like:
```bash
$ carthage (bootstrap|update) --use-submodules --no-use-binaries
```
/cc @sagaraya

Disable using prebuilt binaries for Carthage managed dependencies

---

APIKit.xcodeproj/project.pbxproj
APIKit.xcworkspace/contents.xcworkspacedata
circle.yml

Would address https://github.com/ishkawa/APIKit/issues/40#issuecomment-108680317.
@ishkawa Is this what you intended?

Set up workspace for building dependencies

---

.gitmodules
APIKit.xcodeproj/project.pbxproj
APIKit.xcworkspace/contents.xcworkspacedata
Cartfile.private
Cartfile.resolved
DemoApp/GitHub.swift
DemoApp/Models.swift

__Disclosure:__ I am the author of [that library](https://github.com/ikesyo/Himotoki).
This simplifies the implementations in DemoApp.

Use Himotoki as a JSON decoder in DemoApp

---

.gitmodules
APIKit.xcodeproj/project.pbxproj
APIKit.xcworkspace/contents.xcworkspacedata
Cartfile.private
Cartfile.resolved
DemoApp/GitHub.swift
DemoApp/Models.swift
README.md
circle.yml

##77ca075
@pocket7878 pocket7878 authored 22 days ago

!lu#77ca075 

---

APIKit/API.swift
APIKit/URLEncodedSerialization.swift

Change the argument of stringFromObject()

---

APIKit.xcodeproj/project.pbxproj

Add `APIError.swift` to Compile Sources

---

APIKit/APIError.swift
APIKit/Request.swift
APIKit/RequestBodyBuilder.swift
APIKit/ResponseBodyParser.swift
APIKit/URLEncodedSerialization.swift

Please see each commit for the details. :wink:

Updates for Xcode 7 beta 4

---

APIKit/API.swift
APIKit/Request.swift

`stringByAppendingPathComponent()` is unavailable on `String`.

Updates for Xcode 7 beta 5

---

APIKit.podspec
APIKit.xcodeproj/project.pbxproj
Demo.playground/Contents.swift
README.md

- Fix instructions to install
- Not create API subclass in README and demo
- Add tips about Himotoki

Refine README and demo

---

APIKit.xcodeproj/project.pbxproj
APIKit/Request.swift
APIKitTests/RequestTests.swift

Fix parameter encoding in GET request

---

README.md

The syntax is slightly changed. :wink:

[README] Update a example of Himotoki

---

.travis.yml

[Travis] Stop email notifications

---

.travis.yml

See http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests for the details.

Prevent CI failure caused by pull requests sent from forked repositories

---

README.md

To match with [Himotoki 1.0.0](https://github.com/ikesyo/Himotoki/releases/tag/1.0.0).

[README] Update sample code for Himotoki

---

Demo.playground/Contents.swift

I add debugPrint like the Alamofire.playground.
https://github.com/Alamofire/Alamofire/blob/master/Alamofire.playground/section-1.swift

Fix typo and add debugPrint

---

APIKit.xcodeproj/project.pbxproj
APIKit/API.swift
APIKit/RequestType.swift
APIKitTests/APITests.swift
APIKitTests/RequestCreateTaskInURLSessionTests.swift
APIKitTests/RequestTests.swift
Demo.playground/Contents.swift

Rename Request protocol to RequestType for consistency with Swift standard library

---

APIKit/RequestType.swift
APIKit/URLEncodedSerialization.swift
APIKitTests/RequestCreateTaskInURLSessionTests.swift
APIKitTests/RequestTests.swift
README.md

Improve nullable keys handling, restore [String: AnyObject] for `parameters`

---

Cartfile.resolved

Update dependency to fix installing via Carthage

---

Cartfile
Cartfile.resolved

Update Result to 0.6.0-beta.6

---

README.md

Installation Carthage does not work. Replace 1.0.0-beta4 with 1.0.0-beta.14.

Update README Installation version

---

Cartfile
Cartfile.resolved

Update Result to 1.0.0

---

.travis.yml

- Fix broken build log due to too long log by `pod repo update`.
- Use `pod lib lint` to lint podspec.

Refine .travis.yml

---

Configurations/APIKit.xcconfig

Add APPLICATION_EXTENSION_API_ONLY = YES to APIKit.xcconfig

---

README.md

:pencil2: Change install version to `1.2.1`.

Update README.md : install version

---

APIKit.podspec
APIKit.xcodeproj/project.pbxproj
Sources/APIKit.h
Sources/BodyParametersType/AbstractInputStream.m
Sources/BodyParametersType/MultipartFormDataBodyParameters.swift
Tests/APIKit/BodyParametersType/MultipartFormDataParametersTests.swift
Tests/APIKit/BodyParametersType/NSData+NSInputStream.swift

NSStream-based multipart/form-data implementation

---

Sources/Error/RequestError.swift
Sources/Error/SessionTaskError.swift
Sources/RequestType.swift
Sources/Session.swift
Sources/SessionAdapterType/NSURLSessionAdapter.swift
Sources/SessionAdapterType/SessionAdapterType.swift
Tests/APIKit/RequestTypeTests.swift
Tests/APIKit/SessionAdapterType/NSURLSessionAdapterTests.swift
Tests/APIKit/SessionTests.swift
Tests/APIKit/TestComponents/TestRequest.swift
Tests/APIKit/TestComponents/TestSessionAdapter.swift
Tests/APIKit/TestComponents/TestSessionTask.swift

As @matsuda mentioned in #165, #163 introduced difficulty of customizing NSURLRequest. I have revert #163 first, and picked some other tiny improvements from the PR.

Reverts #163 to keep NSURLRequest customizable

---

APIKit.xcodeproj/project.pbxproj
Sources/BodyParametersType/MultipartFormDataBodyParameters.swift
Sources/BodyParametersType/NSData+NSInputStream.swift
Tests/APIKit/BodyParametersType/MultipartFormDataParametersTests.swift

This PR adds entity type option to MultipartFormDataBodyParameters.

Customizable entity type of multipart/form-data

---

Sources/RequestType.swift
Tests/APIKit/RequestTypeTests.swift
Tests/APIKit/TestComponents/TestRequest.swift

[2.0] Use return value of interceptURLRequest(_:)

---

.travis.yml
APIKit.xcodeproj/project.pbxproj

Disable whole module optimization to avoid build error while `carthage build`

---

.travis.yml

Build matrix for Xcode 7.3 and Xcode 8

---

Sources/Session.swift

Rename the remaining `Req` to `Request`

---

Sources/APIKit/SessionAdapter/URLSessionAdapter.swift

Session has resume task in func send

func createTask don't need resume task

---

Documentation/APIKit2MigrationGuide.md
Documentation/DefiningRequestProtocolForWebService.md
Sources/APIKit/Request.swift

It could be more readable with ~= operator.

Use ~= operator for CountableRange

---

APIKit.podspec
Cartfile
Cartfile.resolved
Package.resolved
Package.swift

Update Result version

---

.travis.yml
Package@swift-4.2.swift
Sources/APIKit/BodyParameters/MultipartFormDataBodyParameters.swift

Support Xcode 10 and Swift 4.2

---

README.md

Remove to link Result.framework from README.md

---

.travis.yml
Configurations/APIKit.xcconfig

https://swift.org/blog/swift-5-1-released/#module-stability
Closes #277.

[Swift 5.1] Enable Module Stability

---

.travis.yml
Sources/APIKit/Session.swift
Sources/APIKit/SessionAdapter/URLSessionAdapter.swift

Remove unnecessary code

---

APIKit.xcodeproj/project.pbxproj

The reference and name of the PBXGroup is wrong and has been corrected.
***Related issues***
#284

fix PBXGroup reference at the project.pbxproj file

---

APIKit.xcodeproj/project.pbxproj
Sources/APIKit/Combine/Combine.swift
Sources/APIKit/Session.swift
Tests/APIKitTests/Combine/CombineTests.swift

Add support for Combine.framework

---

Demo.playground/contents.xcplayground

Fix Demo.playground could not be run
